### Send POST request with json body
POST http://localhost:8080/upperCaseName
Content-Type: application/json

{

  "name": "javier gomez"
}

###

# curl -H "Content-Type: text/plain" localhost:8080/uppercase -d Hello
POST localhost:8080/uppercase
Content-Type: text/plain

Hello

###

GET localhost:8080/time

###

# curl -H "Content-Type: text/plain" localhost:8080/uppercase -d Hello
POST localhost:8080/reverse
Content-Type: text/plain

Hello

###

# this is how you invoke the spring.cloud.function.definition

POST localhost:8080
Content-Type: text/plain

hola pepe lower

###