

### Send POST request with json body
POST https://spring-function-vilz3brbpa-uc.a.run.app
Content-Type: text/plain

Javier gomez

###

### Send POST request with json body
POST https://spring-function-vilz3brbpa-uc.a.run.app/reverse
Content-Type: text/plain

Javier gomez

###


GET https://spring-function-vilz3brbpa-uc.a.run.app/time


###

GET http://localhost:8080/time


###

GET http://localhost:8080/gettime2


###

GET http://localhost:8080/getcars


###

